version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=welcome1
      - MYSQL_DATABASE=zeatful
    ports:
      - 3306:3306

# using this for easy administration of the db in the container
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080